### ISSUE TITLE
client does not automatically re-authenticate when token expires

### ISSUE THREAD

**Issue by akshatprakash** [sypht-team/sypht-java-client#4]
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2019-07-24T01:41:46Z. Current time: 2019-07-24T03:58:47Z, a difference of 8221763 milliseconds.  Allowed clock skew: 0 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:411)
	at com.sypht.SyphtClient.decodeTokenClaims(SyphtClient.java:204)
	at com.sypht.SyphtClient.getBearerToken(SyphtClient.java:181)
	at com.sypht.SyphtClient.createAuthorizedPost(SyphtClient.java:168)
	at com.sypht.SyphtClient.performUpload(SyphtClient.java:124)
	at com.sypht.SyphtClient.upload(SyphtClient.java:86)

in order to re-authenticate a new SyphtClient() object has to be assigned

**Comment by simonmittag** [comment]
Could not reproduce this issue in the current version, tokens refresh fine here. Is this still a bug?
